# Generated by Django 4.1.5 on 2023-01-23 08:55

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("AdminBoundary", "0003_alter_ward_municipality"),
    ]

    operations = [
        migrations.CreateModel(
            name="DisasterType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("icon", models.CharField(max_length=255)),
                ("type", models.CharField(max_length=255)),
                ("order", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Rating",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Disaster",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("geom", django.contrib.gis.db.models.fields.GeometryField(srid=4326)),
                ("registered_date_time", models.DateTimeField()),
                ("update_date_time", models.DateTimeField()),
                ("is_verified", models.BooleanField(default=False)),
                ("is_closed", models.BooleanField(default=False)),
                ("source", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("start_time", models.DateTimeField()),
                ("expire_time", models.DateTimeField()),
                (
                    "municipality",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="AdminBoundary.municipality",
                    ),
                ),
                (
                    "rating",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="DisasterEvents.rating",
                    ),
                ),
                (
                    "type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="DisasterEvents.disastertype",
                    ),
                ),
                (
                    "ward",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="AdminBoundary.ward",
                    ),
                ),
            ],
        ),
    ]
