# Generated by Django 4.1.5 on 2023-01-07 15:07

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("disasterApp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="disaster",
            name="geom",
            field=django.contrib.gis.db.models.fields.GeometryField(
                blank=True, null=True, srid=4326
            ),
        ),
        migrations.AddField(
            model_name="disaster",
            name="municipality",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="disasterApp.local",
            ),
        ),
    ]
