# Generated by Django 4.1.5 on 2023-01-10 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("disasterApp", "0002_delete_run"),
    ]

    operations = [
        migrations.CreateModel(
            name="Run",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
    ]
