# Generated by Django 4.1.5 on 2023-01-23 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("AdminBoundary", "0002_ward"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ward",
            name="Municipality",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="AdminBoundary.municipality",
            ),
        ),
    ]
